version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - JWT_SECRET=change-me
      - STUB_MODE=true
      - AUTO_CLOSE_ENABLED=true
      - CONFIDENCE_THRESHOLD=0.78
    depends_on:
      - mongo

  client:
    build: ./client
    restart: unless-stopped
    ports:
      - "3000:5173"
    depends_on:
      - server

volumes:
  mongo-data:
