version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    # Railway handles networking internally → no need to expose port
    environment:
      MONGO_INITDB_DATABASE: helpdesk

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017/helpdesk
      JWT_SECRET: ${JWT_SECRET:-super-secret-key}
      STUB_MODE: ${STUB_MODE:-true}
      AUTO_CLOSE_ENABLED: ${AUTO_CLOSE_ENABLED:-true}
      CONFIDENCE_THRESHOLD: ${CONFIDENCE_THRESHOLD:-0.78}
    depends_on:
      - mongo

  client:
    build: ./client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      # IMPORTANT: replace with your Railway server URL after first deploy
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
    depends_on:
      - server

volumes:
  mongo-data:
